# Generated by Django 4.1.1 on 2022-09-14 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=245)),
                ('main_pop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pop.pop')),
            ],
        ),
    ]
