# Generated by Django 4.1.1 on 2022-09-14 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pop',
            name='main_pop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pop.pop'),
        ),
    ]
