# Generated by Django 4.1.1 on 2022-10-18 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pop', '0002_alter_pop_main_pop'),
    ]

    operations = [
        migrations.AddField(
            model_name='pop',
            name='input_power',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pop',
            name='total_user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
