# Generated by Django 4.1.1 on 2022-11-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrapper',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='wrapper',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
