# Generated by Django 4.1.1 on 2022-11-13 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountants', '0003_companyprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='profit',
            field=models.FloatField(),
        ),
    ]
