# Generated by Django 4.1.1 on 2022-10-12 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onu',
            name='serial',
        ),
    ]
