# Generated by Django 4.1.1 on 2022-10-12 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_warehouse_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='price',
        ),
    ]
