# Generated by Django 4.1.1 on 2022-09-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='client_id',
            field=models.IntegerField(unique=True),
        ),
    ]
