# Generated by Django 4.1.1 on 2022-11-02 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employ', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employ',
            name='phone',
            field=models.CharField(max_length=100, unique=True, verbose_name='phone'),
        ),
    ]
